hyperparameters:
  --d_model: 128
  dropout: 0.1
  p_rank: 0.1
  p_alpha: 0.2
  d_attn: 8
  apply_positional_encoding: True

optimization:
  batch_size: 512
  epochs: 1500
  learning_rate: 0.001

gpu_setting:
  use_gpu: True
  gpu_id: 0